version: '3.8'

services:
  django-corporate-dashboard:
    image: django-corporate-dashboard:dev
    build:
      context: ./django-corporate-dashboard
    container_name: django-corporate-dashboard
    expose:
      - "1000"

  django-datta-able:
    image: django-datta-able:dev
    build:
      context: ./django-datta-able
    container_name: django-datta-able
    expose:
      - "2000"

  django-modernize:
    image: django-modernize:dev
    build:
      context: ./django-modernize
    container_name: django-modernize
    expose:
      - "3000"

  django-volt-dashboard:
    image: django-volt-dashboard:dev
    build:
      context: ./django-volt-dashboard
    container_name: django-volt-dashboard
    expose:
      - "4000"

  flask-adminlte:
    image: flask-adminlte:dev
    build:
      context: ./flask-adminlte
    container_name: flask-adminlte
    expose:
      - "5000"

  html5up-fractal:
    image: html5up-fractal:dev
    build:
      context: ./html5up-fractal
    container_name: html5up-fractal
    expose:
      - "6000"

  sample-django-extended-user-profile:
    image: sample-django-extended-user-profile:dev
    build:
      context: ./sample-django-extended-user-profile
    container_name: sample-django-extended-user-profile
    expose:
      - "7000"

  # Service Nginx (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - C:/Users/Mohamed/Documents/ESTIAM/ESTIAM/KUBERNETIS/tpprojet/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django-corporate-dashboard
      - django-datta-able
      - django-modernize
      - django-volt-dashboard
      - flask-adminlte
      - html5up-fractal
      - sample-django-extended-user-profile
